"""Generating the CLAUDE.md files that carry the vault into a session.

Two of them, both written from scratch on every launch: one for the vault as a
whole and one for the project being opened. Regenerating rather than patching is
what keeps them honest -- only notes that exist are imported, so there is never
a dangling import and never a drift between the loader and the notes it points
at. It is also why they say DO NOT EDIT and mean it.
"""
from __future__ import annotations

from pathlib import Path

from .paths import short_path
from .vault.locations import Locations
from .vault.model import Entry

HEADER = (
    "# {title}\n\n"
    "Auto-generated by `ccl` on launch — DO NOT EDIT (overwritten every run). {note}\n\n"
)

VAULT_TITLE = "OV Brain — vault-wide context"
VAULT_NOTE = ("House rules and shared user context, loaded for every project "
              "launched via `ccl`.")
PROJECT_NOTE = "Imports this project's OV notes so they load into context at startup."


def render(title: str, note: str, candidates: list[Path]) -> str:
    """The loader's exact text.

    Paths go through short_path, so a note under home is imported as `~/...` and
    one anywhere else by absolute path. The reference wrote
    `p.relative_to(HOME)` unconditionally, which raised ValueError the moment a
    note sat outside the home directory -- unreachable while the vault was
    hardcoded to ~/Projects/OV, and a crash on the first launch after someone
    configured a vault at /srv or on a mounted volume.

    Claude Code accepts both forms: "Both relative and absolute paths are
    allowed", per its memory documentation.

    Only printable paths are imported. A directory name may legally contain a
    newline, and rendered verbatim it would end the @import line early and hand
    the rest to the loader as its own content -- injected lines in a file that
    is auto-loaded into every session.
    """
    imports = "\n".join(f"@{short_path(p)}" for p in candidates
                        if p.exists() and short_path(p).isprintable())
    return HEADER.format(title=title, note=note) + imports + "\n"


def _write(target: Path, text: str) -> Path:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return target


def vault_candidates(locations: Locations) -> list[Path]:
    return [locations.conventions, locations.shared_about_me]


def project_candidates(locations: Locations, entry: Entry) -> list[Path]:
    """This project's notes, in the order they should reach the context.

    The company's About_Me comes last and only when the project names a company,
    which is also what the readiness gates require -- so a launchable project
    always has one.
    """
    candidates = [
        locations.project_note(entry.name),
        locations.environment(entry.name),
        locations.glossary(entry.name),
    ]
    if entry.company:
        candidates.append(locations.company_about_me(entry.company))
    return candidates


def write_vault_loader(locations: Locations) -> Path:
    """Regenerate the vault-wide loader: house rules and shared user context."""
    return _write(locations.vault_loader,
                  render(VAULT_TITLE, VAULT_NOTE, vault_candidates(locations)))


def write_project_loader(locations: Locations, entry: Entry) -> Path:
    """Regenerate one project's loader: its own notes and its company's."""
    return _write(locations.project_loader(entry.name),
                  render(f"{entry.name} — project brain", PROJECT_NOTE,
                         project_candidates(locations, entry)))
